server:
  use-forward-headers: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
          
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud  
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: false
  mvc:
    servlet:
      load-on-startup: 1
      
devtools:
    livereload:
      enabled: true

test:
  property: test6666
