eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
          
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud  

test:
  property: test6666
