server:
  port: 8761
  use-forward-headers: true
  
spring:
  profiles: ide
  boot:
    admin:
      ui:
        publicUrl: localhost:9080/admin
  
eureka:
  instance:
    hostname: localhost        
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
