server:
  port: 8761

server:
  use-forward-headers: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    
zuul:
  sensitive-headers:
  - Cookie
  - Set-Cookie   
  routes:
    good:
      path: /good/**
      stripPrefix: true
      sensitiveHeaders:
      serviceId: API-GOOD
    api-good:
      path: /api-good/**
      serviceId: API-GOOD
    oauth:
      path: /oauth/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: SECURITY
  add-proxy-headers: true

management:  
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

logging:
  level:
    - com.netflix.zuul: debug

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    enabled: false
  mvc:
    servlet:
      load-on-startup: 1
