server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost        
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
