zuul:
  routes:
    good:
      path: /good/**
      stripPrefix: true
      sensitiveHeaders:
      serviceId: API-GOOD
    api-good:
      path: /api-good/**
      serviceId: API-GOOD
    oauth:
      path: /oauth/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: SECURITY
  add-proxy-headers: true

management:  
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

logging:
  level:
    - com.netflix.zuul: debug

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
